# Generated by Django 5.0.6 on 2025-11-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0004_randomchatqueueentry_randomchatsession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomchatqueueentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='randomchatsession',
            name='participant_a',
        ),
        migrations.RemoveField(
            model_name='randomchatsession',
            name='participant_b',
        ),
        migrations.DeleteModel(
            name='RandomChatMessage',
        ),
        migrations.DeleteModel(
            name='RandomChatQueueEntry',
        ),
        migrations.DeleteModel(
            name='RandomChatSession',
        ),
    ]
